### ISSUE TITLE
Automate cargo publish on version update

### ISSUE THREAD

**Issue by FriedlandAaron** [FriedlandAaron/rs_snake#12]
As the title says, I would like to use Github Actions to automate `cargo publish` when a new version is ready. For this, I need to familiarize myself with tags and releases in Git, and then create an appropriate Action when a release is made.

**Comment by ArielHorwitz** [comment]
I recommend taking a look at [cargo-release](https://github.com/crate-ci/cargo-release).

```
cargo release minor
```

**Comment by FriedlandAaron** [comment]
Added Github workflow that uses cargo-release in order to:
- Update crate version and publish to crates.io
- Commit changes to Cargo.toml
- Create Git version tag
- Push changes to repo

Currently triggered manually, will eventually add automatic trigger once I decide what the trigger should be.

Reference to PR of implementation: #19 
SHA of last commit after fixing bugs: 174dd7fe7c407a81418e9036f12dd6da6b8168c9
